### ISSUE TITLE
Output in STATA

### ISSUE THREAD

**Issue by giuliofrey** [chaisemartinPackages/twowayfeweights#8]
Please provide an intuitive way to save the results of the command in STATA. `estout` and `outreg2` currently are not able to do so.

For the moment I used the workaround of writing the output to a log file:

```STATA
log using "table.txt", replace
twowayfeweights Y D state year, type(feTR)
log close
```

**Comment by DiegoCiccia** [comment]
Hello Giulio,
Thanks for your interest in twowayfeweights!
Following your request, we have updated the twowayfeweights with a sub command, "twowayfeweights_out", designed to save the table result as a TeX file. A tutorial on how to use this command as well as how to integrate twowayfeweights with esttab can be found in this [vignette](https://github.com/chaisemartinPackages/twowayfeweights/blob/main/vignettes/vignette_1.md).

In order to use the command with these new features, you should reinstall the package by running:
ssc install twowayfeweights, replace

Let me know what you think!
Best,
Diego

**Comment by giuliofrey** [comment]
Thanks Diego for the quick fix. I reinstalled the package and everything works. Thanks also for the new vignette and the update of the `help` page.
